function usrpTransmit(hexString, fs)
    clc;
    time_scope = timescope(SampleRate=fs);
    modData = [];

    [modData, sof, eof] = modulateHexString(hexString, fs);
    [carrier1, carrier0] = generateCarrierData(modData);
    
    modData = modData';

    sine_data = generateSine();
    time_scope(modData.*sine_data);
    % time_scope([carrier0;carrier1;modData;carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1]);
    
    % %% set up usrp
    % connectedRadios = findsdru;
    % if strncmp(connectedRadios(1).Status, 'Success', 7)
    %     platform = connectedRadios(1).Platform;
    % 
    %     address = connectedRadios(1).IPAddress;
    % 
    % end
    % compileIt  = true; % true if code is to be compiled for accelerated execution
    % useCodegen = true; % true to run the latest generated mex file
    % 
    % radio = comm.SDRuTransmitter(Platform = "N200/N210/USRP2", ...
    %     IPAddress =  '192.168.10.3', ...
    %     CenterFrequency = 13.56*1e6, ...
    %     Gain = 80, ...
    %     MasterClockRate = 100*1e6, ...
    %     InterpolationFactor = 4);
    % disp("Transmitting!");
    % for i = 1:1:200
    %     radio([carrier0;carrier1;modData;carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1;eof';carrier1;eof';...
    %         carrier1]);
    % end
    % disp("Done Transmitting!");
    % release(radio);
end