function usrpTransmit(hexString, fs, ask_percent)
    clc;
    time_scope = timescope(SampleRate=fs);
    InterpolationFactor = round(100e+06/fs);
    disp(InterpolationFactor);
    [modData, sof, eof] = modulateHexString(hexString, fs, ask_percent);
    slot = generateSlotData(fs);
    modData = modData';
    data = [slot;modData;slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot;eof';slot;eof';...
            slot];

    sine_data = generateSine(fs, length(data));
    data = data.*sine_data;
    % time_scope(abs(data));
    
    %% set up usrp
    connectedRadios = findsdru;
    if strncmp(connectedRadios(1).Status, 'Success', 7)
        platform = connectedRadios(1).Platform;

        address = connectedRadios(1).IPAddress;

    end
    compileIt  = true; % true if code is to be compiled for accelerated execution
    useCodegen = true; % true to run the latest generated mex file
    
    radio = comm.SDRuTransmitter(Platform = "N200/N210/USRP2", ...
        IPAddress =  '192.168.10.3', ...
        CenterFrequency = 13.56*1e6, ...
        Gain = 0, ...
        MasterClockRate = 100*1e6, ...
        InterpolationFactor = InterpolationFactor);
    disp("Transmitting!");
    for i = 1:1:100
        radio(data);
    end
    disp("Done Transmitting!");
    release(radio);
end